import { describe, expect, it } from "vitest";

import { createRepositoryDocument } from "../repositories/repository-document.js";
import { isGeneratedRepositoryDocument } from "./generated-repository-document.js";

const createDocument = (path: string, content = "") =>
  createRepositoryDocument(path, content);

const createContentWithMarkerAtLine = (
  lineNumber: number,
  marker: string,
  separator = "\n",
): string =>
  [...Array.from({ length: lineNumber - 1 }, () => "normal line"), marker].join(
    separator,
  );

describe("isGeneratedRepositoryDocument", () => {
  it("recognizes client.generated.ts", () => {
    expect(
      isGeneratedRepositoryDocument(createDocument("src/client.generated.ts")),
    ).toBe(true);
  });

  it("matches generated basenames case-insensitively", () => {
    expect(
      isGeneratedRepositoryDocument(createDocument("src/CLIENT.GENERATED.TS")),
    ).toBe(true);
  });

  it("recognizes a basename ending in .generated", () => {
    expect(
      isGeneratedRepositoryDocument(createDocument("types.generated")),
    ).toBe(true);
  });

  it("does not classify a generated directory name", () => {
    expect(
      isGeneratedRepositoryDocument(createDocument("generated/client.ts")),
    ).toBe(false);
  });

  it.each(["src/generated-client.ts", "src/mygenerated.ts"])(
    "does not classify the regular basename %s",
    (documentPath) => {
      expect(isGeneratedRepositoryDocument(createDocument(documentPath))).toBe(
        false,
      );
    },
  );

  it("recognizes @generated in the first 20 lines", () => {
    expect(
      isGeneratedRepositoryDocument(
        createDocument("src/index.ts", "// @generated by a tool"),
      ),
    ).toBe(true);
  });

  it("matches @Generated case-insensitively", () => {
    expect(
      isGeneratedRepositoryDocument(
        createDocument("src/index.ts", "// @Generated"),
      ),
    ).toBe(true);
  });

  it.each([
    "Code generated by a tool. DO NOT EDIT.",
    "This file was automatically generated. Do not edit.",
    "AUTO-GENERATED FILE — DO NOT EDIT",
  ])("recognizes the strong generated header %j", (header) => {
    expect(
      isGeneratedRepositoryDocument(createDocument("src/index.ts", header)),
    ).toBe(true);
  });

  it("does not classify automatically generated without do not edit", () => {
    expect(
      isGeneratedRepositoryDocument(
        createDocument(
          "src/index.ts",
          "This file was automatically generated.",
        ),
      ),
    ).toBe(false);
  });

  it("does not classify do not edit without a generation phrase", () => {
    expect(
      isGeneratedRepositoryDocument(
        createDocument("src/index.ts", "Configuration file. Do not edit."),
      ),
    ).toBe(false);
  });

  it("requires both strong signals on the same line", () => {
    expect(
      isGeneratedRepositoryDocument(
        createDocument(
          "src/index.ts",
          "This file was automatically generated.\nDo not edit.",
        ),
      ),
    ).toBe(false);
  });

  it("recognizes a marker on line 20", () => {
    expect(
      isGeneratedRepositoryDocument(
        createDocument(
          "src/index.ts",
          createContentWithMarkerAtLine(20, "// @generated"),
        ),
      ),
    ).toBe(true);
  });

  it("ignores a marker on line 21", () => {
    expect(
      isGeneratedRepositoryDocument(
        createDocument(
          "src/index.ts",
          createContentWithMarkerAtLine(21, "// @generated"),
        ),
      ),
    ).toBe(false);
  });

  it.each([
    ["LF", "\n"],
    ["CRLF", "\r\n"],
    ["CR", "\r"],
  ] as const)("recognizes %s logical line separators", (_name, separator) => {
    expect(
      isGeneratedRepositoryDocument(
        createDocument(
          "src/index.ts",
          createContentWithMarkerAtLine(2, "// @generated", separator),
        ),
      ),
    ).toBe(true);
  });

  it("does not classify pnpm-lock.yaml without a marker", () => {
    expect(
      isGeneratedRepositoryDocument(
        createDocument("pnpm-lock.yaml", "lockfileVersion: '9.0'\n"),
      ),
    ).toBe(false);
  });

  it("does not classify an empty document", () => {
    expect(isGeneratedRepositoryDocument(createDocument("src/empty.ts"))).toBe(
      false,
    );
  });

  it("ignores a generated-code mention outside the header", () => {
    expect(
      isGeneratedRepositoryDocument(
        createDocument(
          "src/index.ts",
          createContentWithMarkerAtLine(
            21,
            "This file was automatically generated. Do not edit.",
          ),
        ),
      ),
    ).toBe(false);
  });
});
